targets:
  $default:
    builders:
      moor_generator:
        options:
          apply_converters_on_variables: true
          generate_connect_constructor: true
          override_hash_and_equals_in_result_sets: true
          sqlite_modules:
            - fts5
            - moor_ffi
      json_serializable:
        options:
          explicit_to_json: true
