name: flutter_app
description: A new Flutter project.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  mixin_bot_sdk_dart:
    git: https://github.com/MixinNetwork/mixin_bot_sdk_dart.git
    # local path
  #    path: ../mixin_bot_sdk_dart
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.12.2
  qr_flutter: ^3.2.0
  uuid: ^2.2.2
  cryptography: ^1.4.1
  web_socket_channel: ^1.1.0
  moor: ^3.4.0
  sqlite3_flutter_libs: ^0.3.0
  libsignal_protocol_dart: ^0.2.0
  path_provider: ^1.6.27
  path: ^1.7.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  cached_network_image: ^2.5.0
  very_good_analysis: ^1.0.4
  desktop_window: ^0.3.0
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  intl: ^0.17.0-nullsafety.2
  flutter_svg: ^0.19.2+1
  tuple: ^1.0.3
  archive: ^2.0.13
  hydrated_bloc: ^6.1.0
  rxdart: ^0.25.0
  json_annotation: ^3.1.1
  provider: ^4.3.3
  isolate: ^2.0.3
  dio: ^3.0.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  hive_generator: ^0.8.2
  moor_generator: ^3.4.1
  build_runner: ^1.10.11
  json_serializable: ^3.5.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    # assets start

    # GENERATED CODE - DO NOT MODIFY MANUALLY
    # **************************************************************************
    # Auto generated by https://github.com/fluttercandies/assets_generator
    # **************************************************************************

    - assets/images/

  # assets end
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  class_name: Localization
  use_deferred_loading: true
