name: flutter_app
description: A new Flutter project.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  mixin_bot_sdk_dart:
    git:
      url: https://github.com/MixinNetwork/mixin_bot_sdk_dart.git
      ref: 43d24d4d283f9705fda122a72cb7c8536e58916b
    # local path
  #    path: ../mixin_bot_sdk_dart
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.0
  qr_flutter: ^3.2.0
  uuid: ^3.0.0
  cryptography: ^1.4.1
  web_socket_channel: ^2.0.0
  moor: ^4.1.0
  sqlite3_flutter_libs: ^0.4.0+1
  libsignal_protocol_dart: ^0.2.1
  path_provider: ^2.0.0
  path: ^1.8.0
  hive: ^1.6.0-nullsafety.2
  hive_flutter: ^1.0.0-nullsafety.0
  cached_network_image: ^2.5.0
  very_good_analysis: ^2.0.0-nullsafety.0
  desktop_window: ^0.3.0
  bloc: ^7.0.0-nullsafety.2
  flutter_bloc: ^7.0.0-nullsafety.2
  equatable: ^2.0.0-nullsafety.3
  intl: ^0.17.0
  flutter_svg: ^0.21.0-nullsafety.0
  tuple: ^2.0.0-nullsafety.0
  archive: ^3.0.0
  hydrated_bloc: ^7.0.0-nullsafety.1
  rxdart: ^0.26.0-nullsafety.1
  json_annotation: ^4.0.0
  provider: ^5.0.0-nullsafety.5
  isolate: ^2.0.3
  dio: ^3.0.10
  scrollable_positioned_list: ^0.1.9
  recase: ^4.0.0-nullsafety.0
  file_selector: ^0.8.0
  # file_selector_platform_interface: ^1.0.3+1
  file_selector_macos: ^0.0.4
  file_selector_windows: ^0.0.2
  file_selector_linux: ^0.0.2
  mime: ^1.0.0
  url_launcher: ^6.0.1
  filesize: ^1.0.4
  flutter_portal: ^0.4.0-nullsafety.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
dependency_overrides:
  build_runner: ^1.11.5
  web_socket_channel: ^2.0.0
  tuple: ^2.0.0-nullsafety.0
#  cryptography: ^2.0.0-nullsafety.2
  fixnum: ^1.0.0-nullsafety.0
  crypto: ^3.0.0-nullsafety.0
  convert: ^3.0.0
  http_parser: ^4.0.0
  uuid: ^3.0.0
  recase: ^4.0.0-nullsafety.0
  json_annotation: ^4.0.0
  equatable: ^2.0.0-nullsafety.3
  flutter_cache_manager: ^3.0.0-nullsafety.0
  http: ^0.13.0
  sqflite_common: ^2.0.0
  synchronized: ^3.0.0
  quiver: ^3.0.0

dev_dependencies:
  hive_generator: ^0.9.0-nullsafety.1
  moor_generator: ^4.1.0
  build_runner: ^1.11.5
  json_serializable: ^4.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  # assets start

  # GENERATED CODE - DO NOT MODIFY MANUALLY
  # **************************************************************************
  # Auto generated by https://github.com/fluttercandies/assets_generator
  # **************************************************************************

    - assets/images/

  # assets end
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  class_name: Localization
  use_deferred_loading: true

analyzer:
  plugins:
    - moor
