name: mixin-desktop
version: 0.17.6+0
summary: Mixin Desktop
description: Mixin Messenger

confinement: strict
base: core18
grade: stable

slots:
  dbus-super-cool-app: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.bar.super_cool_app # adjust accordingly to your app name and

apps:
  mixin-desktop:
    command: mixin_desktop
    extensions: [ flutter-master ]
    plugs:
      - network
parts:
  mixin-desktop:
    source: .
    plugin: flutter
    build-packages:
      - libappindicator3-dev
      - gir1.2-appindicator3-0.1
      - libvlc-dev
      - libsqlite3-dev
      - libwebkit2gtk-4.0-dev
      - curl
      - unzip
      - zip
      - xz-utils
      - clang
      - cmake
      - ninja-build
      - pkg-config
      - libgtk-3-dev
    stage-packages:
      - gir1.2-appindicator3-0.1
      - sqlite3
      - vlc
    flutter-target: lib/main.dart
    override-build: |
      flutter clean
      snapcraftctl build